# Generated by Django 5.2.5 on 2025-08-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='christiancontacto',
            name='habilidades',
            field=models.TextField(default='No especificado'),
        ),
    ]
